title: Decimal128
baseurl: "/decimal128-www"
tagline: "IEEE 754-2019 compliant decimal128 high-performance software solution created by Miguel."
markdown: kramdown
kramdown:
  input: GFM
exclude:
  - README.md
  - .gitignore
  - .claude
